### ISSUE TITLE
Runner isn't getting auth, response 404

### ISSUE THREAD

**Issue by brtduvally** [sokube/github-runner-k8s#2]
I may be setting something wrong in the deployment.yml, but I'm getting a 404 not found when it's trying to auth to get the token. 

I only seem to get a token if I add the repo to the URL.  After it not working in the deployment I am testing with curl on the commandline. Example:

Without repo: 
```
# curl -sX POST -H "Authorization: token XXXXXXXXXXX" https://api.github.com/repos/My-Org-Name/actions/runners/registration-token
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}
```
With repo: 
```
# curl -sX POST -H "Authorization: token XXXXXXXXXXXXX" https://api.github.com/repos/My-Org-Name/private_test/actions/runners/registration-token
{
  "token": "XXXXXXXXXXXXXXX",
  "expires_at": "2020-09-30T11:11:49.896-04:00"
}
```

Secret is set according to the docs. I was able to get SanderKnape's running, but I wanted to try this one for the scalability.

**Comment by fabricev** [comment]
Hello, have you changed the env variable GITHUB_OWNER to reflect your real org ? I just tried with my org and the deployment.yaml (with image format corrected) and it worked fine.

**Comment by brtduvally** [comment]
Yes I did. I'm wondering if it's because these Orgs are part of an Enterprise account. I would hope they all work like regular Orgs, but maybe not. GitHub's docs has instructions for runners at the Enterprise level, but we don't want to do that. They don't make it clear that Org's won't work, but they do point to the Enterprise docs in them.

I may put in a support ticket to GH.  Thank you for your fast response!

**Comment by brtduvally** [comment]
Disregard... typo in org name. I am dumb.

**Comment by fabricev** [comment]
No problem, thx for the feedback! Closing the issue.
